<hr>
<a  class="btn btn-primary" rel="nofollow" href="javascript: window.open('http://www.facebook.com/sharer.php?u=<?php the_permalink();?>&amp;&t=<?php echo urlencode(get_the_title($id)); ?>','popup', 'width=600px,height=400px')" title="Share this post on Facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a>
<a class="btn btn-info" rel="nofollow" href="javascript: window.open('http://twitter.com/share?url=<?php the_permalink(); ?>&text=<?php echo urlencode(get_the_title($id)); ?>','popup', 'width=600px,height=400px')" title="Share this article with your Twitter followers"><i class="fa fa-twitter" aria-hidden="true"></i></a>
<a class="btn btn-danger" rel="nofollow" href="javascript: window.open('http://plus.google.com/share?url=<?php the_permalink(); ?>&t=<?php echo urlencode(get_the_title($id)); ?>','popup', 'width=600px,height=400px')"><i class="fa fa-google-plus"></i></a>
<a class="btn btn-danger" rel="nofollow" href="http://pinterest.com/pin/create/button/?url=<?php the_permalink(); ?>&description=<?php the_title(); ?>"><i class="fa fa-pinterest"></i></a>
<a class="btn btn-primary hidden-xs" rel="nofollow" href="http://digg.com/submit?phase=2&amp;url=<?php the_permalink(); ?>" title="Submit this post to Digg"><i class="fa fa-digg" aria-hidden="true"></i></a>
<a class="btn btn-primary hidden-xs" rel="nofollow" href="http://www.stumbleupon.com/submit?url=<?php the_permalink(); ?>&amp;title=<?php echo urlencode(get_the_title($id)); ?>" title="Share this post at StumbleUpon"><i class="fa fa-stumbleupon" aria-hidden="true"></i></a>
<a class="btn btn-primary hidden-xs" rel="nofollow" href="http://reddit.com/submit?url=<?php the_permalink(); ?>&amp;title=<?php echo urlencode(get_the_title($id)); ?>" title="Share this post on Reddit"><i class="fa fa-reddit-alien" aria-hidden="true"></i></a>
<a class="btn btn-primary hidden-xs" rel="nofollow" href="http://www.linkedin.com/shareArticle?mini=true&url=<?php the_permalink(); ?>&title=<?php the_title() ?>&summary=<?php the_excerpt(); ?>&source=<?php bloginfo('url') ?>"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
<a class="btn btn-success" rel="nofollow" href="whatsapp://send?text=<?php the_permalink(); ?>"><i class="fa fa-whatsapp" aria-hidden="true"></i></a>